config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'genres#index'
  resources :users, only: [:edit, :update]
  resources :genres, only: [:new, :create, :edit, :update] do
    resources :posts, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_users
  has_many :users, through: :genre_users
  has_many :posts
  validates :name, presence: true, uniqueness: true
end

app/models/genre_user.rb
class GenreUser < ApplicationRecord
  belongs_to :genre
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :genre
  belongs_to :user

  validates :reason, presence: true, unless: :video?

  mount_uploader :video, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :genre_users
  has_many :genres, through: :genre_users
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
  end

  def new
    @genre = Genre.new
    @genre.users << current_user
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to root_path, notice: '新しいジャンルを作成しました'
    else
      render :new
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genre_posts_path(@genre), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, user_ids: [])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_genre

  def index
    @post = Post.new
    @posts = @genre.posts.includes(:user).order("created_at DESC")
  end

  def create
    @post = @genre.posts.new(post_params)
    
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url

    if @post.save
      redirect_to genre_posts_path(@genre), notice:'メッセージが送信されました'
    else
      @posts = @genre.posts.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def post_params
    params.require(:post).permit(:reason, :youtube_url, :video).merge(user_id: current_user.id)
  end

  def set_genre
    @genre = Genre.find(params[:genre_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/genres/_form.html.haml
= form_for genre do |f|
  - if genre.errors.any?
    .mv-genre-form__errors
      %h2= "#{genre.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - genre.errors.full_messages.each do |message|
          %li= message
  .mv-genre-form__field
    .mv-genre-form__field--left
      = f.label :name, class: 'mv-genre-form__label'
    .mv-genre-form__field--right
      = f.text_field :name, class: 'mv__genre_name mv-genre-form__input', placeholder: 'ジャンルを入力してください'
  .mv-genre-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .mv-genre-form__field.clearfix
    .mv-genre-form__field--left
      %label.mv-genre-form__label{:for => "mv_genre_ジャンルメンバー"} ジャンルメンバー
    .mv-genre-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .mv-genre-form__field.clearfix
    .mv-genre-form__field--left
    .mv-genre-form__field--right
      = f.submit class: 'mv-genre-form__action-btn'

app/views/genres/edit.html.haml
.mv-genre-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { genre: @genre }

app/views/genres/index.html.haml
.wrapper
  = render 'posts/side_bar'

app/views/genres/new.html.haml
.mv-genre-form
  %h1 新しいジャンルを追加しよう！
  = render partial: 'form', locals: { genre: @genre }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Mybias2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/_main_post.html.haml
.chat-main

  .main-header
    .main-header__left-box
      %h.main-header__left-box__current-group
        = @genre.name
      %h.main-header__left-box__member-list
        Member：
        - @genre.users.each do |user|
          = "#{user.name} "
    .main-header__edit-btn
      = link_to edit_genre_path(@genre), class:"btn" do
        Edit

  .form
    = form_for [@genre, @post] do |f|
      .input-box
        紹介したいYoutubeのURLと、選出理由を書いてね！
        %br
        (YoutubeのURLは、末尾が"="以下11桁のURLをご利用ください。)
        = f.text_field :youtube_url, class:"input-box__url", placeholder:"type a Youtube url"
        = f.text_field :reason, class: 'input-box__reason', placeholder: 'type a reason'
        -# = f.label :video, class: 'input-box__image' do
        -#   = icon('far', 'file-video')
        -#   = f.file_field :video, class: 'input-box__image__file'
        = f.submit 'Send', class: 'submit-btn'
        
  .posts
    = render @posts

app/views/posts/_post.html.haml
.posts
  .post
    .post__upper-info
      %p.post__upper-info__talker
        = post.user.name
      %p.post__upper-info__date
        = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
    %p.post__text
      - if post.reason.present?
        %p.post__text__youtube_url
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/#{post.youtube_url}", :width => "560"}
        %p.post__text__reason
          選出理由：
          %br
          = post.reason
      -# = video_tag post.video.url, class: 'lower-post__video' if post.video.present?

app/views/posts/_side_bar.html.haml
.chat-side
  .side-header
    .side-header__title
      = image_tag('logo-mybias.png', options = {alt: 'mybias', height: '80px', width: '240px', class: ''})
    .side-header__box
      %p.side-header__box__user-name
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu__new-group
          = link_to new_genre_path do
            = icon('far', 'edit',class: "icon")
        %li.side-header__box__menu__edit-user
          = link_to edit_user_path(current_user) do
            = icon('fas', 'cog', class: 'icon')
  .genres
    - current_user.genres.each do |genre|
      .genre
        = link_to genre_posts_path(genre) do
          .genre__genre-name
            = genre.name
          .genre__latest-post
            -# メッセージはまだありません。

app/views/posts/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_post"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      = image_tag('w-logo-mybias.png', options = {alt: 'mybias', height: '80px', width: '240px', class: ''})
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'